#!/bin/sh

cp ~/.config/foot/foot.ini ./foot/
cp ~/.config/sway/config ./sway/
cp ~/.fonts/* ./fonts
cp ~/.config/user-dirs.dirs ./user-dirs.dirs/user-dirs.dirs 2>/dev/null
cp ~/.vimrc ./vim/.vimrc 2>/dev/null
rm ./wallpaper.jpg 2>/dev/null; cp ~/imagenes/wallpaper.png ./wallpaper.png 2>/dev/null|| rm ./wallpaper.png 2>/dev/null; cp ~/imagenes/wallpaper.jpg ./wallpaper.jpg 2>/dev/null
