#!/bin/sh

cp ~/.config/sway/config ./sway/config
cp ~/.config/foot/foot.ini ./foot/foot.ini
cp ~/.bashrc ./home/.bashrc
cp ~/.bash_profile ./home/.bash_profile
cp ~/.config/user-dirs.dirs ./user-dirs.dirs/user-dirs.dirs
cp ~/.vimrc ./vim/.vimrc
cp ~/.config/okpal . -r
rm ./wallpaper.jpg 2>/dev/null; cp ~/imagenes/wallpaper.png ./wallpaper.png 2>/dev/null|| rm ./wallpaper.png 2>/dev/null; cp ~/imagenes/wallpaper.jpg ./wallpaper.jpg 2>/dev/null
