#!/bin/sh

cp ~/.config/foot/foot.ini ./foot/
cp ~/.config/sway/config ./sway/
rm ./fonts/*
cp ~/.fonts/* ./fonts
cp ~/.config/user-dirs.dirs ./user-dirs.dirs/user-dirs.dirs 2>/dev/null
cp ~/.vimrc ./vim/.vimrc 2>/dev/null
cp ~/imagenes/wallpapers/* ./wallpapers/
